#!/bin/bash

# script/setup
#
# Sets up dependencies required to link/use dotfiles.

# Install GNU Stow via Homebrew
# https://www.gnu.org/software/stow
brew install stow

# Install rbenv
# https://github.com/rbenv/rbenv
brew install rbenv

# Install rbenv-default-gems
# https://github.com/rbenv/rbenv-default-gems
brew install rbenv-default-gems

# Install yarn
# https://yarnpkg.com/en/
brew install yarn

# Install vim
# with Python3 support (necessary for denite.vim)
brew install vim --with-python3

# Install [exuberant] ctags
# http://ctags.sourceforge.net
brew install ctags

# Install CMake
# https://cmake.org
# A dependency for the rugged gem (which is a dependency for pronto).
# https://github.com/libgit2/rugged#install
brew install cmake

# Install switchaudio-osx
# https://github.com/deweller/switchaudio-osx
brew install switchaudio-osx

# Install terminal-notifier
# https://github.com/julienXX/terminal-notifier
brew install terminal-notifier

# Install reattach-to-user-namespace
# https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
brew install reattach-to-user-namespace

# Install hub
# https://hub.github.com/
brew install hub
