#!/bin/bash

# script/unlink <dotfiles>
#
# Ex:
#   script/unlink tmux

# Exit immediately if a command exits with a non-zero status.
set -e

# Change directory to parent directory of this script.
cd "$(dirname "$0")/.."

# Stow the specified dotfiles.
stow -t ~/ -D -vv $1
